#pragma once

#define SAMPLE_RATE 48000
#define NUM_CHANNELS 2
#define MAX_FILES 32
#define FRAMES_PER_BUFFER 0x100
#define VIZ_BUFFER_SIZE FRAMES_PER_BUFFER * NUM_CHANNELS
#define MAX_VOLUME 1.0f
#define FP_IN_VEC 4 // sizeof(__m128) / sizeof(float)
#define NUM_BUFFERS_POW_2 3
#define NUM_FILES_POW_2 1

#define PI 3.14159265359f
#define PI_DIV_4 0.78539816339f

#define MAX_DATA_SIZE 0x200000
#define LFO_BUFFER_SIZE 1024

#define MAX_LPF_FREQ 20000.0f
#define DEFAULT_LPF_Q 0.707f

#define DEFAULT_PITCH_DEVIATION 0
#define MAX_PITCH_DEVIATION 12
#define MIN_PITCH_DEVIATION 0
#define DEFAULT_VOLUME_LOWER_BOUND 0
#define MIN_VOLUME_LOWER_BOUND 0
#define MAX_VOLUME_LOWER_BOUND 90
#define DEFAULT_WALK_SPEED 4
#define MAX_WALK_SPEED 12
#define MIN_WALK_SPEED 1
#define DEFAULT_LPF_FREQ_DEVIATION 0
#define MIN_LPF_FREQ_DEVIATION 0
#define MAX_LPF_FREQ_DEVIATION 19
#define DEFAULT_LPF_Q_DEVIATION 0
#define MIN_LPF_Q_DEVIATION 0
#define MAX_LPF_Q_DEVIATION 8
#define DEFAULT_LFO_FREQ 0
#define MIN_LFO_FREQ 1
#define MAX_LFO_FREQ 10
#define DEFAULT_LFO_AMOUNT 100
#define MIN_LFO_AMOUNT 0
#define MAX_LFO_AMOUNT 100